name: Release

on:
  create:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create GitHub Releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Specify your Go version

    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o nino ./...
        tar -czf NINO_${{ steps.get_version.outputs.VERSION }}_linux_amd64.tar.gz nino

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o nino.exe ./...
        tar -czf NINO_${{ steps.get_version.outputs.VERSION }}_windows_amd64.tar.gz nino.exe

    - name: Build for macOS
      run: |
        GOOS=darwin GOARCH=amd64 go build -o nino ./...
        tar -czf NINO_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz nino

    - name: Package example workspace
      run: zip -r NINO_${{ steps.get_version.outputs.VERSION }}_workspace.zip petstore dvdrental

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./NINO_${{ steps.get_version.outputs.VERSION }}_linux_amd64.tar.gz
        asset_name:  NINO_${{ steps.get_version.outputs.VERSION }}_linux_amd64.tar.gz
        asset_content_type: application/tar+gzip

    - name: Upload Workspace release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./NINO_${{ steps.get_version.outputs.VERSION }}_workspace.zip
        asset_name:  NINO_${{ steps.get_version.outputs.VERSION }}_workspace.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./NINO_${{ steps.get_version.outputs.VERSION }}_windows_amd64.tar.gz
        asset_name:  NINO_${{ steps.get_version.outputs.VERSION }}_windows_amd64.tar.gz
        asset_content_type: application/tar+gzip

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./NINO_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz
        asset_name:  NINO_${{ steps.get_version.outputs.VERSION }}_darwin_amd64.tar.gz
        asset_content_type: application/tar+gzip