name: Release

on:
  create:
    tags:
      - 'v*' # Trigger on tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create GitHub Releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # Specify your Go version

    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o nino-linux-amd64 ./...
        zip nino-linux-amd64.zip nino-linux-amd64

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o nino-windows-amd64.exe ./...
        zip nino-windows-amd64.zip nino-windows-amd64.exe

    - name: Build for macOS
      run: |
        GOOS=darwin GOARCH=amd64 go build -o nino-darwin-amd64 ./...
        zip nino-darwin-amd64.zip nino-darwin-amd64

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.ref }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nino-linux-amd64.zip
        asset_name: nino-linux-amd64-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nino-windows-amd64.zip
        asset_name: nino-windows-amd64-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (macOS)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nino-darwin-amd64.zip
        asset_name: nino-darwin-amd64-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip